import{a as L,S as v,i as d}from"./assets/vendor-5401a4b0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const t of o)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function r(o){const t={};return o.integrity&&(t.integrity=o.integrity),o.referrerPolicy&&(t.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?t.credentials="include":o.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(o){if(o.ep)return;o.ep=!0;const t=r(o);fetch(o.href,t)}})();async function p(s,e){const r="https://pixabay.com/api/";return(await L.get(r,{params:{key:"42530845-4f1978a0628226c655e2788d5",q:`${s}`,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}const g=document.querySelector(".gallery");function w({largeImageURL:s,webformatURL:e,tags:r,likes:n,views:o,comments:t,downloads:c}){return`<a class = 'img-box' href="${s}">
                <img src="${e}" alt="${r}"/>
                <div class="info-box">
                    <p class="info"><b>Likes</b> ${n}</p>
                    <p class="info"><b>Views</b> ${o}</p>
                    <p class="info"><b>Comments</b> ${t}</p>
                    <p class="info"><b>Downloads</b> ${c}</p>
                </div>
            </a>`}function h(s){const e=s.map(w).join("");return g.insertAdjacentHTML("beforeend",e)}const u="/goit-js-hw-12/assets/icon-8fe9c699.svg",m=document.querySelector(".form"),i=document.querySelector(".loading"),a=document.querySelector(".load-more");function S(){const e=document.querySelector(".img-box").getBoundingClientRect();if(e.height>0){let r=e.height*2;window.scrollBy({top:r,behavior:"smooth"})}}const y=new v(".gallery a",{captionsData:"alt",captionDelay:100});let l,f;function b(s){const e=s.totalHits/15;f>=e&&(a.classList.add("hidden"),d.show({iconUrl:u,message:"We're sorry, but you've reached the end of search results",messageColor:"#ffffff",color:"#1e81b0",position:"topRight",progressBarColor:"#ffffff",close:!1,timeout:5e3}))}m.addEventListener("submit",x);async function x(s){if(s.preventDefault(),g.innerHTML="",l=m.search.value.trim().replace(/\s/g,"+"),l&&l!==""){f=1,i.classList.add("loader");try{const e=await p(l,f);e.totalHits!==0?(i.classList.remove("loader"),h(e.hits),y.refresh(),a.classList.remove("hidden"),b(e)):(d.show({iconUrl:u,message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#ffffff",color:"#FF6868",position:"topRight",progressBarColor:"#ffffff",close:!1,timeout:5e3}),i.classList.remove("loader"),a.classList.add("hidden"))}catch(e){d.show({iconUrl:u,message:`Sorry, there is a problem - ${e}!`,messageColor:"#ffffff",color:"#FF7F50",position:"topRight",progressBarColor:"#ffffff",close:!1,timeout:5e3}),console.log(e),i.classList.remove("loader")}finally{m.reset()}}else{a.classList.add("hidden");return}}a.addEventListener("click",q);async function q(){a.classList.add("hidden"),i.classList.add("loader"),f++;const s=await p(l,f);i.classList.remove("loader"),h(s.hits),S(),a.classList.remove("hidden"),y.refresh(),b(s)}
//# sourceMappingURL=commonHelpers.js.map
