import{a as L,S as b,i as f}from"./assets/vendor-5401a4b0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const t of o)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function a(o){const t={};return o.integrity&&(t.integrity=o.integrity),o.referrerPolicy&&(t.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?t.credentials="include":o.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(o){if(o.ep)return;o.ep=!0;const t=a(o);fetch(o.href,t)}})();async function g(s,e){const a="https://pixabay.com/api/";return(await L.get(a,{params:{key:"42530845-4f1978a0628226c655e2788d5",q:`${s}`,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}const h=document.querySelector(".gallery");function v({largeImageURL:s,webformatURL:e,tags:a,likes:l,views:o,comments:t,downloads:n}){return`<a class = 'img-box' href="${s}">
                <img src="${e}" alt="${a}"/>
                <div class="info-box">
                    <p class="info"><b>Likes</b> ${l}</p>
                    <p class="info"><b>Views</b> ${o}</p>
                    <p class="info"><b>Comments</b> ${t}</p>
                    <p class="info"><b>Downloads</b> ${n}</p>
                </div>
            </a>`}function y(s){const e=s.map(v).join("");return h.insertAdjacentHTML("beforeend",e)}const d="/goit-js-hw-12/assets/icon-8fe9c699.svg",u=document.querySelector(".form"),i=document.querySelector(".loading"),r=document.querySelector(".load-more");function w(){const e=document.querySelector(".img-box").getBoundingClientRect();if(e.height>0){let a=e.height*2;window.scrollBy({top:a,behavior:"smooth"})}}const p=new b(".gallery a",{captionsData:"alt",captionDelay:100});let c,m;u.addEventListener("submit",S);async function S(s){if(s.preventDefault(),h.innerHTML="",c=u.search.value.trim().replace(/\s/g,"+"),c&&c!==""){m=1,i.classList.add("loader");try{const e=await g(c,m);e.total!==0?(i.classList.remove("loader"),y(e.hits),p.refresh(),r.classList.remove("hidden"),e.totalHits<15&&r.classList.add("hidden")):(f.show({iconUrl:d,message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#ffffff",color:"#FF6868",position:"topRight",progressBarColor:"#ffffff",close:!1,timeout:5e3}),i.classList.remove("loader"),r.classList.add("hidden"))}catch(e){f.show({iconUrl:d,message:`Sorry, there is a problem - ${e}!`,messageColor:"#ffffff",color:"#FF7F50",position:"topRight",progressBarColor:"#ffffff",close:!1,timeout:5e3}),console.log(e),i.classList.remove("loader")}finally{u.reset()}}else{r.classList.add("hidden");return}}r.addEventListener("click",x);async function x(){i.classList.add("loader"),r.classList.add("hidden"),m++;try{const s=await g(c,m);i.classList.remove("loader"),y(s.hits),w(),r.classList.remove("hidden"),p.refresh(),s.hits.length<15&&(r.classList.add("hidden"),f.show({iconUrl:d,message:`"We're sorry, but you've reached the end of search results`,messageColor:"#ffffff",color:"#1e81b0",position:"topRight",progressBarColor:"#ffffff",close:!1,timeout:5e3}))}catch(s){f.show({iconUrl:d,message:`Sorry, there is a problem - ${s}!`,messageColor:"#ffffff",color:"#FF7F50",position:"topRight",progressBarColor:"#ffffff",close:!1,timeout:5e3}),console.log(s),i.classList.remove("loader")}}
//# sourceMappingURL=commonHelpers.js.map
